apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hfjxwa46z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hfjxwa46z-go 
  name: hfjxwa46z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hfjxwa46z-go 
